// BankNav「海外电话卡」完整地区栏目（2026-09-25）；不含其「平台卡」分类及实体 eSIM 写卡工具。
// cycle 只在来源明确给出间隔时设置；未给出间隔的卡片留给用户填写。
const PAGES = [
  "https://www.banknav.com/post/favorites/%E5%85%A8%E9%83%A8esim/",
  "https://www.banknav.com/post/favorites/%E5%85%A8%E9%83%A8esim/page/2/",
  "https://www.banknav.com/post/favorites/%E5%85%A8%E9%83%A8esim/page/3/",
];

function card(region, name, rule, cycle, unit, page, extra = {}) {
  return {
    id: `${region}:${name}`,
    region,
    name,
    rule,
    cycle,
    unit,
    sourceUrl: PAGES[page],
    ...extra,
  };
}

function siteCard(region, name, rule, cycle, unit, siteId) {
  return card(region, name, rule, cycle, unit, 0, {
    sourceUrl: `https://www.banknav.com/sites/${siteId}.html`,
  });
}

export const PHONE_CARDS = [
  card(
    "英国",
    "CTExcel",
    "每半年发一条短信保号（BankNav 标价 0.1）。",
    6,
    "month",
    0,
  ),
  card(
    "英国",
    "giffgaff",
    "每 180 天使话费余额变动一次；发短信或充值均可。",
    180,
    "day",
    0,
    { sourceUrl: "https://www.banknav.com/post/1216/" },
  ),
  card(
    "英国",
    "VOXI",
    "每 180 天发一条短信保号（BankNav 标价 £0.08）。",
    180,
    "day",
    0,
  ),
  card("英国", "LycaMobile", "BankNav 未给出明确保号期限。", null, null, 0),
  card(
    "英国",
    "CMLink UK",
    "BankNav 仅注明 0 月租，未给出保号期限。",
    null,
    null,
    0,
  ),
  card(
    "香港",
    "月神卡",
    "优惠套餐首月后可改为 9 HKD 月租；按实际月费续费。",
    1,
    "month",
    0,
  ),
  card("香港", "Club SIM", "每年购买 6 HKD 短信组合保号。", 1, "year", 0),
  card(
    "香港",
    "大湾区预付费卡",
    "每 180 天充值一次 50 元保号。",
    180,
    "day",
    0,
  ),
  card("香港", "haha SIM", "每年充值 10 HKD 且消费一次。", 1, "year", 0),
  card("香港", "3HK DIY 大湾区", "每年购买 268 HKD 套餐保号。", 1, "year", 0),
  card(
    "德国",
    "Vodafone",
    "每 90 天充值一次；BankNav 称最低可充 €0.01。",
    90,
    "day",
    0,
  ),
  card(
    "荷兰",
    "Vodafone",
    "每 180 天使余额变动一次，可通过发短信或充值完成。",
    180,
    "day",
    0,
    { sourceUrl: "https://www.banknav.com/post/9643/" },
  ),
  card(
    "新西兰",
    "2degrees",
    "转为 Prepay 后，每年充值 10 NZD 保号。",
    1,
    "year",
    0,
  ),
  card("菲律宾", "GlobeOne", "每年充值 20 PHP 保号。", 1, "year", 0),
  card("菲律宾", "Smart", "每年充值 10 PHP 保号。", 1, "year", 0),
  card("菲律宾", "DITO", "每年充值 5 PHP 保号。", 1, "year", 0),
  card("爱沙尼亚", "eSIM.gg", "BankNav 标注无需保号。", null, null, 0, {
    noRenewal: true,
  }),
  card("爱沙尼亚", "eSIM Plus", "BankNav 标注无需保号。", null, null, 0, {
    noRenewal: true,
  }),
  card(
    "新西兰",
    "One NZ",
    "开卡后初始有效期 4 年；此后每年充值 10 NZD。",
    1,
    "year",
    0,
    { initialCycle: 4, initialUnit: "year" },
  ),
  card("澳门", "Easy+ 预付卡", "BankNav 未给出明确保号期限。", null, null, 0),
  card(
    "澳门",
    "大湾区预付费卡",
    "每 180 天充值一次 50 元保号。",
    180,
    "day",
    0,
  ),
  card("澳门", "CTM", "每 180 天充值 50 MOP 保号。", 180, "day", 0),

  card(
    "瑞士",
    "Yallo",
    "每年发一条短信保号（BankNav 标价 1 CHF）。",
    1,
    "year",
    1,
  ),
  card(
    "瑞士",
    "Lebara",
    "每年发一条短信保号（BankNav 标价 1 CHF）。",
    1,
    "year",
    1,
  ),
  card("德国", "Telekom", "每 15 个月充值至少 €5 保号。", 15, "month", 1),
  card(
    "新西兰",
    "Skinny",
    "每年充值 5 NZD，或在两个 Skinny 号码间互转余额；仅实体卡。",
    1,
    "year",
    1,
  ),
  card("乌克兰", "lifecell", "充值 20 UAH 可保号 365 天。", 365, "day", 1),
  card("乌克兰", "Kyivstar", "一年内充值一次，App 最低 10 UAH。", 1, "year", 1),
  card(
    "美国",
    "Tello",
    "每月支付约 $5 的套餐；按实际账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "美国",
    "Google Voice",
    "BankNav 称可长期使用，未给出保号操作或期限。",
    null,
    null,
    1,
  ),
  card("美国", "Google Fi", "BankNav 未给出明确保号期限。", null, null, 1),
  card(
    "美国",
    "ENC",
    "每月支付约 $3 的套餐；按实际账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "美国",
    "T-Mobile",
    "每月支付约 $3 的套餐；按实际账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "美国",
    "Ultra Mobile",
    "每月支付约 $3 的套餐；按实际账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "美国",
    "Helium Mobile",
    "BankNav 标注 0 月租，未给出保号期限。",
    null,
    null,
    1,
  ),
  card(
    "泰国",
    "AIS",
    "BankNav 称 3.6 USD 可保号 3 年；请核对所购方案。",
    3,
    "year",
    1,
  ),
  card("泰国", "eSIM2Fly", "每充值 10 THB 延长有效期 1 个月。", 1, "month", 1),
  card(
    "泰国",
    "dtac",
    "充值 10–50 THB 可延长有效期；BankNav 未注明延长天数。",
    null,
    null,
    1,
  ),
  card(
    "越南",
    "Vietnamobile",
    "充值 10,000 VND 延长 45 天；充值至少 300,000 VND 延长 405 天。",
    45,
    "day",
    1,
  ),
  card(
    "越南",
    "Viettel",
    "需在越南激活；BankNav 建议 1–3 个月内充值，具体有效期需核对。",
    null,
    null,
    1,
  ),
  card("越南", "MobiFone", "55,000 VND 保号 1 年。", 1, "year", 1),
  card("马来西亚", "Hotlink", "每年支付 30 MYR 保号。", 1, "year", 1),
  card(
    "马来西亚",
    "Tune Talk",
    "购买 35 MYR 套餐，可延长有效期 1 年。",
    1,
    "year",
    1,
  ),
  card("马来西亚", "U Mobile", "每 60 天充值 5 MYR 保号。", 60, "day", 1),
  card(
    "马来西亚",
    "CelcomDigi",
    "套餐结束后有 60 天宽限期，宽限期内充值至少 1 MYR；请按套餐实际结束日设置到期日。",
    60,
    "day",
    1,
  ),
  card(
    "日本",
    "NTT docomo",
    "月租约 ¥2,970 起；按实际套餐账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "日本",
    "KDDI au",
    "月租约 ¥1,000–3,000；按实际套餐账单日续费。",
    1,
    "month",
    1,
  ),
  card(
    "新加坡",
    "M1",
    "5 SGD 可延长有效期 90 天，叠加上限 180 天。",
    90,
    "day",
    1,
  ),
  card(
    "法国",
    "Orange",
    "BankNav 标注无合约套餐保号免费，未给出有效期。",
    null,
    null,
    1,
  ),
  card(
    "日本",
    "Rakuten Mobile",
    "月租约 ¥1,078 起；按实际套餐账单日续费。",
    1,
    "month",
    1,
  ),

  card("法国", "Lebara", "90 天内使余额发生变动。", 90, "day", 2),
  card(
    "新加坡",
    "StarHub",
    "按充值金额或月套餐延长有效期；BankNav 未给出固定天数。",
    null,
    null,
    2,
  ),
  card(
    "韩国",
    "SKT",
    "充值延长有效期；BankNav 未给出固定天数。",
    null,
    null,
    2,
  ),
  card(
    "法国",
    "Free",
    "月租套餐最低约 €2；按实际套餐账单日续费。",
    1,
    "month",
    2,
  ),
  card(
    "日本",
    "SoftBank",
    "定期充值或开月套餐保号；BankNav 未给出固定周期。",
    null,
    null,
    2,
  ),
  card(
    "新加坡",
    "Singtel",
    "游客卡续期需 Singpass 二次验证；BankNav 未给出可通用保号周期。",
    null,
    null,
    2,
  ),
  card(
    "韩国",
    "LG U+",
    "充值延长有效期；BankNav 未给出固定天数。",
    null,
    null,
    2,
  ),
  card("韩国", "KT", "充值延长有效期；BankNav 未给出固定天数。", null, null, 2),
  card(
    "澳大利亚",
    "ALDI Mobile",
    "每年支付 15 AUD 保号（Pay As You Go）。",
    1,
    "year",
    2,
  ),
  card("澳大利亚", "amaysim", "每年支付 15 AUD 保号。", 1, "year", 2),
  card("格鲁吉亚", "Cellfie", "约 3.1 CNY 保号 1 年。", 1, "year", 2),
  card(
    "尼日利亚",
    "MTN",
    "保号可选 1 年 511 NGN、2 年 819 NGN 或 3 年 1128 NGN；默认 1 年，可修改。",
    1,
    "year",
    2,
  ),
  card(
    "奥地利",
    "Educom",
    "每 180 天发一条短信保号（BankNav 标价 €0.35）。",
    180,
    "day",
    2,
  ),
  card("萨尔瓦多", "Tigo", "BankNav 未给出明确保号期限。", null, null, 2),
  card("摩尔多瓦", "Moldtelecom", "约 0.43 CNY 保号 1 年。", 1, "year", 2),
  card("克罗地亚", "A1", "每年支付 €2 保号。", 1, "year", 2),
  card("墨西哥", "Telcel", "每年充值 50 MXN 保号。", 1, "year", 2),
  card(
    "立陶宛",
    "Ežys",
    "每 30 天充值 €1；BankNav 称另有 100 天宽限期。",
    30,
    "day",
    2,
  ),
  card("意大利", "CoopVoce", "每年充值 €5 保号。", 1, "year", 2),

  // 按地区栏目补齐的条目。
  siteCard("英国", "Three", "每 180 天充值任意金额保号。", 180, "day", 13141),
  siteCard(
    "英国",
    "Vodafone",
    "BankNav 标注 10 GBP 月租；请按实际账单日续费。",
    1,
    "month",
    14074,
  ),
  siteCard(
    "英国",
    "Asda Mobile",
    "每 180 天消费一次（发短信或通话），或充值一次。",
    180,
    "day",
    14268,
  ),
  siteCard("德国", "O2", "每 180 天充值一次，最低 €0.01。", 180, "day", 13231),
  siteCard(
    "荷兰",
    "Simyo",
    "每 180 天发一条短信保号，BankNav 标价 €0.50；余额可支付多次保号费用。",
    180,
    "day",
    5445,
  ),
  siteCard(
    "奥地利",
    "Yesss",
    "每半年充值 €5，合计每年约 €10。",
    6,
    "month",
    13572,
  ),
  siteCard(
    "瑞士",
    "Swisscom",
    "每年发一条短信保号，BankNav 标价 0.4 CHF。",
    1,
    "year",
    3452,
  ),
  siteCard(
    "越南",
    "VNSKY",
    "每 30 天内发一条短信保号，BankNav 标价 500 VND/条。",
    30,
    "day",
    13682,
  ),
  siteCard("香港", "CLS 香港电讯", "每年支付 6 HKD 保号。", 1, "year", 13338),
  siteCard(
    "日本",
    "Cuniq",
    "月租 550 JPY；请按实际账单日续费。",
    1,
    "month",
    14503,
  ),
  siteCard(
    "波兰",
    "Play",
    "BankNav 提到 30 PLN 套餐，但明确标注保号期限未知；请自行核对。",
    null,
    null,
    14697,
  ),
  siteCard("捷克", "kaktus", "每年充值 50 CZK 保号。", 1, "year", 14555),
  siteCard(
    "奥地利",
    "Lidl eSIM",
    "每 12 个月充值一次，最低 €5。",
    12,
    "month",
    14473,
  ),
  siteCard(
    "冰岛",
    "Nova",
    "每 6 个月充值一次；BankNav 标注 App 最低充值 1000 ISK。",
    6,
    "month",
    10428,
  ),
  siteCard(
    "马耳他",
    "Melita",
    "每 365 天使余额发生一次变动。",
    365,
    "day",
    13279,
  ),
  siteCard("意大利", "Spusu", "每年充值 €5 保号。", 1, "year", 13137),
  siteCard(
    "加拿大",
    "Fizz",
    "BankNav 未列出固定保号操作或期限；请按实际套餐核对。",
    null,
    null,
    12111,
  ),
  siteCard(
    "塞尔维亚",
    "Yettel",
    "BankNav 写作“11月充值一次”，最低 300 RSD；表述有歧义，请核对周期后手动填写。",
    null,
    null,
    13285,
  ),
  siteCard(
    "马其顿",
    "Telekom",
    "不同充值金额增加不同有效期；BankNav 未给出统一周期，请手动填写。",
    null,
    null,
    13340,
  ),
  siteCard(
    "哈萨克斯坦",
    "Tele2",
    "BankNav 标注每月保号费用约 0.015 CNY；请按实际账单日核对。",
    1,
    "month",
    2446,
  ),
  siteCard(
    "捷克",
    "O2",
    "充值至少 300 CZK 一次，可延长有效期 1 年。",
    1,
    "year",
    13342,
  ),
  siteCard(
    "乌拉圭",
    "Antel",
    "BankNav 未给出保号操作或期限；请自行核对。",
    null,
    null,
    13491,
  ),
  siteCard(
    "巴林",
    "STC",
    "充值超过 30 BHD 可延长 100 天；BankNav 另提到每年保留使用记录。",
    100,
    "day",
    13577,
  ),
  siteCard(
    "萨摩亚",
    "Digicell",
    "BankNav 未给出保号操作或期限；请自行核对。",
    null,
    null,
    13575,
  ),
  siteCard(
    "巴西",
    "Vivo",
    "每 30–90 天保持一次消费动作，如发短信或充值；请按所购方案手动设置周期。",
    null,
    null,
    13583,
  ),
  siteCard(
    "波黑",
    "Novotel",
    "充值 1–1.99 KM 延长 3 天，2–2.99 KM 延长 8 天，3–4.99 KM 延长 15 天，5–9.99 KM 延长 30 天，10–19.99 KM 延长 90 天，20–50 KM 延长 120 天；请按充值金额手动设置周期。",
    null,
    null,
    13586,
  ),
  siteCard(
    "斯洛文尼亚",
    "Telekom",
    "每 270 天内至少充值一次。",
    270,
    "day",
    13660,
  ),
  siteCard("斯里兰卡", "Dialog", "每年充值 1000 LKR 保号。", 1, "year", 13665),
  siteCard("西班牙", "Llamaya", "每 105 天充值 €5 保号。", 105, "day", 13972),
];
