import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const postcss = require("postcss");
const tailwindcss = require("tailwindcss");
let html = await readFile(
  new URL("../web/index.html", import.meta.url),
  "utf8",
);
const frontend = await readFile(
  new URL("../web/app.js", import.meta.url),
  "utf8",
);
const flags = await readFile(
  new URL("../web/flags.js", import.meta.url),
  "utf8",
);
const phoneCards = (
  await readFile(new URL("../shared/phone-cards.js", import.meta.url), "utf8")
).replace(/^export /gm, "");
// Only compile handlers from our own HTML source, never from user data. The
// served page has no inline JavaScript and can use a self-only script CSP.
const handlers = [];
html = html.replace(/<[^>]+>/g, (tag) => {
  const events = [
    ...tag.matchAll(/\s(onclick|onchange|oninput|onsubmit)="([^"]*)"/g),
  ];
  if (!events.length) return tag;
  const id = handlers.length;
  for (const [, name, body] of events)
    handlers.push(
      `document.querySelector('[data-ui="${id}"]').addEventListener('${name.slice(2)}', function(event) { ${body} });`,
    );
  return tag
    .replace(/\s(onclick|onchange|oninput|onsubmit)="[^"]*"/g, "")
    .replace(/^(<\w+)/, `$1 data-ui="${id}"`);
});
const dates = (
  await readFile(new URL("../shared/dates.js", import.meta.url), "utf8")
).replace(/^export /gm, "");
const css = (
  await postcss([
    tailwindcss({
      content: [
        { raw: html, extension: "html" },
        { raw: frontend, extension: "js" },
      ],
      theme: { extend: {} },
      plugins: [],
    }),
  ]).process(
    await readFile(new URL("../web/styles.css", import.meta.url), "utf8"),
    { from: undefined },
  )
).css;
const crypto = await readFile(
  require.resolve("crypto-js/crypto-js.js"),
  "utf8",
);
const assets = {
  "/": { type: "text/html; charset=utf-8", body: html },
  "/app.js": {
    type: "application/javascript; charset=utf-8",
    body:
      dates +
      "\n" +
      flags +
      "\n" +
      phoneCards +
      "\n" +
      frontend +
      "\n" +
      handlers.join("\n"),
  },
  "/styles.css": { type: "text/css; charset=utf-8", body: css },
  "/crypto-js.js": {
    type: "application/javascript; charset=utf-8",
    body: crypto,
  },
};
await mkdir(new URL("../worker", import.meta.url), { recursive: true });
await writeFile(
  new URL("../worker/generated-ui.js", import.meta.url),
  "// Generated by npm run build.\nexport default " +
    JSON.stringify(assets) +
    ";\n",
);
console.log(
  "Built HTML, local styles, browser logic and backup compatibility library.",
);
